language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update --prefer-source $PREFER_LOWEST

script: vendor/bin/phpunit --coverage-text
