name: Tests

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - "8.2"
          - "8.3"
        symfony:
          - "^6.4"
          - "^7.0"
        include:
          - php: "8.1"
            symfony: "^6.4"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer requirements
        run: composer require -W "symfony/serializer:${{ matrix.symfony }}"

      - name: Setup Problem Matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run PHPStan
        run: vendor/bin/phpstan

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox --coverage-text
